"""Corrigiendo timestamp de publicaciones

Revision ID: 5a33bf4c386c
Revises: f3c9ab82c528
Create Date: 2025-02-13 17:14:58.765971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a33bf4c386c'
down_revision = 'f3c9ab82c528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # <--- Asegúrate de que no intente eliminar nada más
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # <--- No se restaurará nada
    # ### end Alembic commands ###
